project:
  type: website
  output-dir: docs

website:
  title: "Marketing Analytics"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd  
        text: Resume  
      - href: projects.qmd  # <-- add this
        text: Projects
      - href: hw1_questions.qmd  # <-- add this
        text: Blogs


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



